<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['en_name' => 'Afghanistan', 'ar_name' => 'أفغانستاني'],
            ['en_name' => 'Albanian', 'ar_name' => 'ألباني'],
            ['en_name' => 'Aland Islander', 'ar_name' => 'آلاندي'],
            ['en_name' => 'Algerian', 'ar_name' => 'جزائري'],
            ['en_name' => 'American Samoan', 'ar_name' => 'أمريكي سامواني'],
            ['en_name' => 'Andorran', 'ar_name' => 'أندوري'],
            ['en_name' => 'Angolan', 'ar_name' => 'أنقولي'],
            ['en_name' => 'Anguillan', 'ar_name' => 'أنغويلي'],
            ['en_name' => 'Antarctican', 'ar_name' => 'أنتاركتيكي'],
            ['en_name' => 'Antiguan', 'ar_name' => 'بربودي'],
            ['en_name' => 'Argentinian', 'ar_name' => 'أرجنتيني'],
            ['en_name' => 'Armenian', 'ar_name' => 'أرميني'],
            ['en_name' => 'Aruban', 'ar_name' => 'أوروبهيني'],
            ['en_name' => 'Australian', 'ar_name' => 'أسترالي'],
            ['en_name' => 'Austrian', 'ar_name' => 'نمساوي'],
            ['en_name' => 'Azerbaijani', 'ar_name' => 'أذربيجاني'],
            ['en_name' => 'Bahamian', 'ar_name' => 'باهاميسي'],
            ['en_name' => 'Bahraini', 'ar_name' => 'بحريني'],
            ['en_name' => 'Bangladeshi', 'ar_name' => 'بنغلاديشي'],
            ['en_name' => 'Barbadian', 'ar_name' => 'بربادوسي'],
            ['en_name' => 'Belarusian', 'ar_name' => 'روسي'],
            ['en_name' => 'Belgian', 'ar_name' => 'بلجيكي'],
            ['en_name' => 'Belizean', 'ar_name' => 'بيليزي'],
            ['en_name' => 'Beninese', 'ar_name' => 'بنيني'],
            ['en_name' => 'Saint Barthelmian', 'ar_name' => 'سان بارتيلمي'],
            ['en_name' => 'Bermudan', 'ar_name' => 'برمودي'],
            ['en_name' => 'Bhutanese', 'ar_name' => 'بوتاني'],
            ['en_name' => 'Bolivian', 'ar_name' => 'بوليفي'],
            ['en_name' => 'Bosnian / Herzegovinian', 'ar_name' => 'بوسني/هرسكي'],
            ['en_name' => 'Botswanan', 'ar_name' => 'بوتسواني'],
            ['en_name' => 'Bouvetian', 'ar_name' => 'بوفيهي'],
            ['en_name' => 'Brazilian', 'ar_name' => 'برازيلي'],
            ['en_name' => 'British Indian Ocean Territory', 'ar_name' => 'إقليم المحيط الهندي البريطاني'],
            ['en_name' => 'Bruneian', 'ar_name' => 'بروني'],
            ['en_name' => 'Bulgarian', 'ar_name' => 'بلغاري'],
            ['en_name' => 'Burkinabe', 'ar_name' => 'بوركيني'],
            ['en_name' => 'Burundian', 'ar_name' => 'بورونيدي'],
            ['en_name' => 'Cambodian', 'ar_name' => 'كمبودي'],
            ['en_name' => 'Cameroonian', 'ar_name' => 'كاميروني'],
            ['en_name' => 'Canadian', 'ar_name' => 'كندي'],
            ['en_name' => 'Cape Verdean', 'ar_name' => 'الرأس الأخضر'],
            ['en_name' => 'Caymanian', 'ar_name' => 'كايماني'],
            ['en_name' => 'Central African', 'ar_name' => 'أفريقي'],
            ['en_name' => 'Chadian', 'ar_name' => 'تشادي'],
            ['en_name' => 'Chilean', 'ar_name' => 'شيلي'],
            ['en_name' => 'Chinese', 'ar_name' => 'صيني'],
            ['en_name' => 'Christmas Islander', 'ar_name' => 'جزيرة عيد الميلاد'],
            ['en_name' => 'Cocos Islander', 'ar_name' => 'جزر كوكوس'],
            ['en_name' => 'Colombian', 'ar_name' => 'كولومبي'],
            ['en_name' => 'Comorian', 'ar_name' => 'جزر القمر'],
            ['en_name' => 'Congolese', 'ar_name' => 'كونغي'],
            ['en_name' => 'Cook Islander', 'ar_name' => 'جزر كوك'],
            ['en_name' => 'Costa Rican', 'ar_name' => 'كوستاريكي'],
            ['en_name' => 'Croatian', 'ar_name' => 'كوراتي'],
            ['en_name' => 'Cuban', 'ar_name' => 'كوبي'],
            ['en_name' => 'Cypriot', 'ar_name' => 'قبرصي'],
            ['en_name' => 'Curacian', 'ar_name' => 'كوراساوي'],
            ['en_name' => 'Czech', 'ar_name' => 'تشيكي'],
            ['en_name' => 'Danish', 'ar_name' => 'دنماركي'],
            ['en_name' => 'Djiboutian', 'ar_name' => 'جيبوتي'],
            ['en_name' => 'Dominican', 'ar_name' => 'دومينيكي'],
            ['en_name' => 'Ecuadorian', 'ar_name' => 'إكوادوري'],
            ['en_name' => 'Egyptian', 'ar_name' => 'مصري'],
            ['en_name' => 'Salvadoran', 'ar_name' => 'سلفادوري'],
            ['en_name' => 'Equatorial Guinean', 'ar_name' => 'غيني'],
            ['en_name' => 'Eritrean', 'ar_name' => 'إريتيري'],
            ['en_name' => 'Estonian', 'ar_name' => 'استوني'],
            ['en_name' => 'Ethiopian', 'ar_name' => 'أثيوبي'],
            ['en_name' => 'Falkland Islander', 'ar_name' => 'فوكلاندي'],
            ['en_name' => 'Faroese', 'ar_name' => 'جزر فارو'],
            ['en_name' => 'Fijian', 'ar_name' => 'فيجي'],
            ['en_name' => 'Finnish', 'ar_name' => 'فنلندي'],
            ['en_name' => 'French', 'ar_name' => 'فرنسي'],
            ['en_name' => 'French Guianese', 'ar_name' => 'غويانا الفرنسية'],
            ['en_name' => 'French Polynesian', 'ar_name' => 'بولينيزيي'],
            ['en_name' => 'Gabonese', 'ar_name' => 'غابوني'],
            ['en_name' => 'Gambian', 'ar_name' => 'غامبي'],
            ['en_name' => 'Georgian', 'ar_name' => 'جيورجي'],
            ['en_name' => 'German', 'ar_name' => 'ألماني'],
            ['en_name' => 'Ghanaian', 'ar_name' => 'غاني'],
            ['en_name' => 'Gibraltar', 'ar_name' => 'جبل طارق'],
            ['en_name' => 'Guernsian', 'ar_name' => 'غيرنزي'],
            ['en_name' => 'Greek', 'ar_name' => 'يوناني'],
            ['en_name' => 'Greenlandic', 'ar_name' => 'جرينلاندي'],
            ['en_name' => 'Grenadian', 'ar_name' => 'غرينادي'],
            ['en_name' => 'Guadeloupe', 'ar_name' => 'جزر جوادلوب'],
            ['en_name' => 'AF', 'ar_name' => 'AF'],
            ['en_name' => 'Guatemalan', 'ar_name' => 'غواتيمالي'],
            ['en_name' => 'Guinean', 'ar_name' => 'غيني'],
            ['en_name' => 'Guinea-Bissauan', 'ar_name' => 'غيني'],
            ['en_name' => 'Guyanese', 'ar_name' => 'غياني'],
            ['en_name' => 'Haitian', 'ar_name' => 'هايتي'],
            ['en_name' => 'Heard and Mc Donald Islanders', 'ar_name' => 'جزيرة هيرد وجزر ماكدونالد'],
            ['en_name' => 'Honduran', 'ar_name' => 'هندوراسي'],
            ['en_name' => 'Hongkongese', 'ar_name' => 'هونغ كونغي'],
            ['en_name' => 'Hungarian', 'ar_name' => 'مجري'],
            ['en_name' => 'Icelandic', 'ar_name' => 'آيسلندي'],
            ['en_name' => 'Indian', 'ar_name' => 'هندي'],
            ['en_name' => 'Manx', 'ar_name' => 'ماني'],
            ['en_name' => 'Indonesian', 'ar_name' => 'أندونيسيي'],
            ['en_name' => 'Iranian', 'ar_name' => 'إيراني'],
            ['en_name' => 'Iraqi', 'ar_name' => 'Iraqi'],
            ['en_name' => 'Irish', 'ar_name' => 'إيرلندي'],
            ['en_name' => 'Italian', 'ar_name' => 'إيطالي'],
            ['en_name' => 'Ivory Coastian', 'ar_name' => 'ساحل العاج'],
            ['en_name' => 'Jersian', 'ar_name' => 'جيرزي'],
            ['en_name' => 'Jamaican', 'ar_name' => 'جمايكي'],
            ['en_name' => 'Japanese', 'ar_name' => 'ياباني'],
            ['en_name' => 'Jordanian', 'ar_name' => 'أردني'],
            ['en_name' => 'Kazakh', 'ar_name' => 'كازاخستاني'],
            ['en_name' => 'Kenyan', 'ar_name' => 'كيني'],
            ['en_name' => 'I-Kiribati', 'ar_name' => 'كيريباتي'],
            ['en_name' => 'North Korean', 'ar_name' => 'كوري'],
            ['en_name' => 'South Korean', 'ar_name' => 'كوري'],
            ['en_name' => 'Kosovar', 'ar_name' => 'كوسيفي'],
            ['en_name' => 'Kuwaiti', 'ar_name' => 'كويتي'],
            ['en_name' => 'Kyrgyzstani', 'ar_name' => 'قيرغيزستاني'],
            ['en_name' => 'Laotian', 'ar_name' => 'لاوسي'],
            ['en_name' => 'Latvian', 'ar_name' => 'لاتيفي'],
            ['en_name' => 'Lebanese', 'ar_name' => 'لبناني'],
            ['en_name' => 'Basotho', 'ar_name' => 'ليوسيتي'],
            ['en_name' => 'Liberian', 'ar_name' => 'ليبيري'],
            ['en_name' => 'Libyan', 'ar_name' => 'ليبي'],
            ['en_name' => 'Liechtenstein', 'ar_name' => 'ليختنشتيني'],
            ['en_name' => 'Lithuanian', 'ar_name' => 'لتوانيي'],
            ['en_name' => 'Luxembourger', 'ar_name' => 'لوكسمبورغي'],
            ['en_name' => 'Sri Lankian', 'ar_name' => 'سريلانكي'],
            ['en_name' => 'Macanese', 'ar_name' => 'ماكاوي'],
            ['en_name' => 'Macedonian', 'ar_name' => 'مقدوني'],
            ['en_name' => 'Malagasy', 'ar_name' => 'مدغشقري'],
            ['en_name' => 'Malawian', 'ar_name' => 'مالاوي'],
            ['en_name' => 'Malaysian', 'ar_name' => 'ماليزي'],
            ['en_name' => 'Maldivian', 'ar_name' => 'مالديفي'],
            ['en_name' => 'Malian', 'ar_name' => 'مالي'],
            ['en_name' => 'Maltese', 'ar_name' => 'مالطي'],
            ['en_name' => 'Marshallese', 'ar_name' => 'مارشالي'],
            ['en_name' => 'Martiniquais', 'ar_name' => 'مارتينيكي'],
            ['en_name' => 'Mauritanian', 'ar_name' => 'موريتانيي'],
            ['en_name' => 'Mauritian', 'ar_name' => 'موريشيوسي'],
            ['en_name' => 'Mahoran', 'ar_name' => 'مايوتي'],
            ['en_name' => 'Mexican', 'ar_name' => 'مكسيكي'],
            ['en_name' => 'Micronesian', 'ar_name' => 'مايكرونيزيي'],
            ['en_name' => 'Moldovan', 'ar_name' => 'مولديفي'],
            ['en_name' => 'Monacan', 'ar_name' => 'مونيكي'],
            ['en_name' => 'Mongolian', 'ar_name' => 'منغولي'],
            ['en_name' => 'Montenegrin', 'ar_name' => 'الجبل الأسود'],
            ['en_name' => 'Montserratian', 'ar_name' => 'مونتسيراتي'],
            ['en_name' => 'Moroccan', 'ar_name' => 'مغربي'],
            ['en_name' => 'Mozambican', 'ar_name' => 'موزمبيقي'],
            ['en_name' => 'Myanmarian', 'ar_name' => 'ميانماري'],
            ['en_name' => 'Namibian', 'ar_name' => 'ناميبي'],
            ['en_name' => 'Nepalese', 'ar_name' => 'نيبالي'],
            ['en_name' => 'Dutch', 'ar_name' => 'هولندي'],
            ['en_name' => 'Dutch Antilier', 'ar_name' => 'هولندي'],
            ['en_name' => 'New Caledonian', 'ar_name' => 'كاليدوني'],
            ['en_name' => 'New Zealander', 'ar_name' => 'نيوزيلندي'],
            ['en_name' => 'Nicaraguan', 'ar_name' => 'نيكاراجوي'],
            ['en_name' => 'Nigerien', 'ar_name' => 'نيجيري'],
            ['en_name' => 'Nigerian', 'ar_name' => 'نيجيري'],
            ['en_name' => 'Niuean', 'ar_name' => 'ني'],
            ['en_name' => 'Norfolk Islander', 'ar_name' => 'نورفوليكي'],
            ['en_name' => 'Northern Marianan', 'ar_name' => 'ماريني'],
            ['en_name' => 'Norwegian', 'ar_name' => 'نرويجي'],
            ['en_name' => 'Omani', 'ar_name' => 'عماني'],
            ['en_name' => 'Pakistani', 'ar_name' => 'باكستاني'],
            ['en_name' => 'Palauan', 'ar_name' => 'بالاوي'],
            ['en_name' => 'Palestinian', 'ar_name' => 'فلسطيني'],
            ['en_name' => 'Panamanian', 'ar_name' => 'بنمي'],
            ['en_name' => 'Papua New Guinean', 'ar_name' => 'بابوي'],
            ['en_name' => 'Paraguayan', 'ar_name' => 'بارغاوي'],
            ['en_name' => 'Peruvian', 'ar_name' => 'بيري'],
            ['en_name' => 'Filipino', 'ar_name' => 'فلبيني'],
            ['en_name' => 'Pitcairn Islander', 'ar_name' => 'بيتكيرني'],
            ['en_name' => 'Polish', 'ar_name' => 'بوليني'],
            ['en_name' => 'Portuguese', 'ar_name' => 'برتغالي'],
            ['en_name' => 'Puerto Rican', 'ar_name' => 'بورتي'],
            ['en_name' => 'Qatari', 'ar_name' => 'قطري'],
            ['en_name' => 'Reunionese', 'ar_name' => 'ريونيوني'],
            ['en_name' => 'Romanian', 'ar_name' => 'روماني'],
            ['en_name' => 'Russian', 'ar_name' => 'روسي'],
            ['en_name' => 'Rwandan', 'ar_name' => 'رواندا'],
            ['en_name' => 'Kittitian/Nevisian', 'ar_name' => 'سانت كيتس ونيفس'],
            ['en_name' => 'St. Martian(French)', 'ar_name' => 'ساينت مارتني فرنسي'],
            ['en_name' => 'St. Martian(Dutch)', 'ar_name' => 'ساينت مارتني هولندي'],
            ['en_name' => 'St. Pierre and Miquelon', 'ar_name' => 'سان بيير وميكلوني'],
            ['en_name' => 'Saint Vincent and the Grenadines', 'ar_name' => 'سانت فنسنت وجزر غرينادين'],
            ['en_name' => 'Samoan', 'ar_name' => 'ساموي'],
            ['en_name' => 'Sammarinese', 'ar_name' => 'ماريني'],
            ['en_name' => 'Sao Tomean', 'ar_name' => 'ساو تومي وبرينسيبي'],
            ['en_name' => 'Saudi Arabian', 'ar_name' => 'سعودي'],
            ['en_name' => 'Senegalese', 'ar_name' => 'سنغالي'],
            ['en_name' => 'Serbian', 'ar_name' => 'صربي'],
            ['en_name' => 'Seychellois', 'ar_name' => 'سيشيلي'],
            ['en_name' => 'Sierra Leonean', 'ar_name' => 'سيراليوني'],
            ['en_name' => 'Singaporean', 'ar_name' => 'سنغافوري'],
            ['en_name' => 'Slovak', 'ar_name' => 'سولفاكي'],
            ['en_name' => 'Slovenian', 'ar_name' => 'سولفيني'],
            ['en_name' => 'Solomon Island', 'ar_name' => 'جزر سليمان'],
            ['en_name' => 'Somali', 'ar_name' => 'صومالي'],
            ['en_name' => 'South African', 'ar_name' => 'أفريقي'],
            ['en_name' => 'South Sudanese', 'ar_name' => 'سوادني جنوبي'],
            ['en_name' => 'Spanish', 'ar_name' => 'إسباني'],
            ['en_name' => 'St. Helenian', 'ar_name' => 'هيلاني'],
            ['en_name' => 'Sudanese', 'ar_name' => 'سوداني'],
            ['en_name' => 'Surinamese', 'ar_name' => 'سورينامي'],
            ['en_name' => 'Swazi', 'ar_name' => 'سوازيلندي'],
            ['en_name' => 'Swedish', 'ar_name' => 'سويدي'],
            ['en_name' => 'Swiss', 'ar_name' => 'سويسري'],
            ['en_name' => 'Syrian', 'ar_name' => 'سوري'],
            ['en_name' => 'Taiwanese', 'ar_name' => 'تايواني'],
            ['en_name' => 'Tajikistani', 'ar_name' => 'طاجيكستاني'],
            ['en_name' => 'Tanzanian', 'ar_name' => 'تنزانيي'],
            ['en_name' => 'Thai', 'ar_name' => 'تايلندي'],
            ['en_name' => 'Timor-Lestian', 'ar_name' => 'تيموري'],
            ['en_name' => 'Togolese', 'ar_name' => 'توغي'],
            ['en_name' => 'Tokelaian', 'ar_name' => 'توكيلاوي'],
            ['en_name' => 'Tongan', 'ar_name' => 'تونغي'],
            ['en_name' => 'Tunisian', 'ar_name' => 'تونسي'],
            ['en_name' => 'Turkish', 'ar_name' => 'تركي'],
            ['en_name' => 'Turkmen', 'ar_name' => 'تركمانستاني'],
            ['en_name' => 'Tuvaluan', 'ar_name' => 'توفالي'],
            ['en_name' => 'Ugandan', 'ar_name' => 'أوغندي'],
            ['en_name' => 'Ukrainian', 'ar_name' => 'أوكراني'],
            ['en_name' => 'Emirati', 'ar_name' => 'إماراتي'],
            ['en_name' => 'British', 'ar_name' => 'بريطاني'],
            ['en_name' => 'American', 'ar_name' => 'أمريكي'],
            ['en_name' => 'Uruguayan', 'ar_name' => 'أورغواي'],
            ['en_name' => 'Uzbek', 'ar_name' => 'أوزباكستاني'],
            ['en_name' => 'Vanuatuan', 'ar_name' => 'فانواتي'],
            ['en_name' => 'Venezuelan', 'ar_name' => 'فنزويلي'],
            ['en_name' => 'Vietnamese', 'ar_name' => 'فيتنامي'],
            ['en_name' => 'Vatican', 'ar_name' => 'فاتيكاني'],
            ['en_name' => 'Sahrawian', 'ar_name' => 'صحراوي'],
            ['en_name' => 'Yemeni', 'ar_name' => 'يمني'],
            ['en_name' => 'Zambian', 'ar_name' => 'زامبياني'],
            ['en_name' => 'Zimbabwean', 'ar_name' => 'زمبابوي'],
        ];

        DB::table('nationalities')->delete();
        foreach ($nationalities as $nationality){
            DB::table('nationalities')->insert(['name'=>$nationality['en_name']]);
        }
    }
}
